apiVersion: apps/v1
kind: Deployment
metadata:
  name: <DIGITALOCEAN_DEPLOYMENT_NAME>
  namespace: rancher-deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <DIGITALOCEAN_DEPLOYMENT_NAME>
  template:
    metadata:
      labels:
        app: <DIGITALOCEAN_DEPLOYMENT_NAME>
    spec:
      containers:
      - name: <DIGITALOCEAN_DEPLOYMENT_NAME>-container
        image: <DIGITALOCEAN_DEPLOYMENT_NAME>
        imagePullSecrets:
        - name: gleo-registry
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: <DIGITALOCEAN_DEPLOYMENT_NAME>-service
  namespace: rancher-deployments
spec:
  selector:
    app: <DIGITALOCEAN_DEPLOYMENT_NAME>
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP